name: Release

on:
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Nerd Fonts
        run: |
          echo "start_time=$(date +%s)" >> $GITHUB_ENV
          mkdir -p /tmp/fonts
          INSTALL_FONTS=(Hack JetBrainsMono)
          for i in ${INSTALL_FONTS[@]}; do
            echo "Downloading font ${i} ==> https://github.com/ryanoasis/nerd-fonts/releases/latest/download/${i}.zip"
            wget -q https://github.com/ryanoasis/nerd-fonts/releases/latest/download/${i}.zip
            echo "Unzipping font ${i}.zip"
            unzip -q -o ${i}.zip -d /tmp/fonts
            rm -rf ${i}.zip
          done
          rm -rf ./fonts
          mkdir -p ./fonts
          cp /tmp/fonts/*Mono-*.ttf ./fonts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          build-args: NODE_VER=${{ github.event.client_payload.node }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.event.client_payload.repo }}:${{ github.event.client_payload.tag }}
          cache-from: type=registry,ref=${{ github.event.client_payload.repo }}:buildcache
          cache-to: type=registry,ref=${{ github.event.client_payload.repo }}:buildcache,mode=max

      - name: Build time
        run: |
          start_time=$(echo ${{ env.start_time }})
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "Build time: $((duration / 60)) minutes and $((duration % 60)) seconds"
          # 通过构建时长来判断 Code Server 是否有更新
          if [ $duration -gt 300 ]; then
            echo "CODE_SERVER_UPDATED=true" >> $GITHUB_ENV
          else
            echo "CODE_SERVER_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Update Changelog
        if: env.CODE_SERVER_UPDATED == 'true'
        run: |
          echo "## [${{ github.event.client_payload.tag }}] - $(date +'%Y-%m-%d')" > CHANGELOG.md
          echo "- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ github.event.client_payload.tag }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@actions.github.com"
          git add CHANGELOG.md
          git commit --allow-empty -m "【$(date +'%Y-%m-%d')】Update changelog for release ${{ github.event.client_payload.tag }}"
          git push
